name:                table-reader
version:             0.1.0.0
github:              "githubuser/table-reader"
license:             BSD3
author:              "Minaki Seirawan"
maintainer:          "example@example.com"
copyright:           "2020 Minaki Seirawan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/table-reader#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson >= 1.4 && < 2
  - text >= 1.2 && < 2

executables:
  table-reader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 1.4 && < 2
    - bytestring >= 0.10 && < 1
    - table-reader
    - text >= 1.2 && < 2

tests:
  table-reader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - table-reader
